### ISSUE TITLE
wish: Use basebox  rather than vagrantboxes

### ISSUE THREAD

**Issue by hedgehog** [garethr/ruby-vagrantboxes#2]
It would be much more consistent with vagrant (and and the veewee extension) to use:

```
vagrant basebox get 'name'
etc.
```

rather than 

```
vagrant vagrantboxes add 1
etc.
```

This way vagrant users have a consistent command interface.
If vagrant is to avoid the bloat, and the load on the developers, of having to provide these extensions itself/themselves, it really is up to extension writers to collaborate and reach mutual accommodations.
Hope this is taken in the right spirit.

update: 
If this is done, `list` would need to take a `--descriptions` option or become the `list-descriptions` command, similarly for any other commands that are ambiguous about wether they refer to the built basebox, or a description of it.
Ultimately it is perhaps easiest to keep a hash of a built base box and the description that built it, auditability, disaster recovery etc. etc. but this is likely down the track ;)

**Comment by garethr** [comment]
I'll have to disagree with your point about consistency I'm afraid. For adding a new box vagrant provides the add box command which has the following signature.

```
vagrant box add NAME URI
```

The vagrantboxes id encapsulates both a NAME and a URI, and is also much quicker to type. Hence the sig:

```
vagrant vagrantboxes ID
```

 I might provide the same interface for just passing in the NAME, but as more of a fallback. At present you can just use vagrantboxes listed boxes by copying the url (and name if you like). The purpose of this extension is really just to make that easier to do from the command line.

I have vague theories about how this might be useful outside the specifics of the vagrantboxes website but went for running code first and can build consensus for a more general tool if time and adoption permits.

With regards this being namespaced under basebox, that risks all sorts of clashes with the veewee extension. The basebox namespace is also currently used for building baseboxes, whereas box is used for managing the resulting box.

I might in the future extend vagrantboxes to allow for better meta data, including the veewee template files. That way you rather than downloading a ready made box, you could download the template that made it. This would be better for some usecases I'll admit.

**Comment by hedgehog** [comment]
Fair enough although I did actually propose `_get_` the consistency is in the use of `vagrant basebox <verb>` rather than the the verb.
Sorry I wasn't clearer.

My update tries to address the case where the `<verb>` is already in existence.  Again sorry for the confusion.
